name: Generate and Deploy PHPDocs

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Download phpDocumentor .phar
        run: |
          curl -LSs https://phpdoc.org/phpDocumentor.phar -o phpDocumentor.phar
          chmod +x phpDocumentor.phar

      - name: Generate PHPDocs
        run: |
          mkdir -p docs/api
          ./phpDocumentor.phar -d lib -t docs/api

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/api

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
